services:
  api:
    build: ./api
    command: npm start
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=localhost
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  api_db:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
    ports:
      - "27017:27017"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: realworld-docker-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    stdin_open: true
    tty: true

  nginx:
    image: nginx:1-alpine
    container_name: websystem-docker-demo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api

volumes:
  mongodb_api: